site_name: "A RuboCop extension focused on enforcing Rails best practices and coding conventions."
repo_url: https://github.com/rubocop-hq/rubocop-rails
edit_uri: edit/master/manual/
copyright: "Copyright &copy; 2012-2019 Bozhidar Batsov and RuboCop contributors"
docs_dir: manual
pages:
- Home: index.md
- Installation: installation.md
- Usage: usage.md
- Cops: cops.md
- Cops Documentation:
    - Rails Cops: cops_rails.md
theme: readthedocs
